# Tu usuario de Ko-fi (solo el nombre, sin la url)
ko_fi: qievenz

# Plataformas personalizadas (aquí van las URLs completas)
custom: [
  "https://ko-fi.com/qievenz",
  "https://cafecito.app/qievenz", 
  "https://paypal.me/qievenz"
]
